spiffe/spiffe-helper

- README.md
Adding banner to indicate this subproject is currently looking for a maintainer. 
In finding a maintainer, it will be important to evaluate the need for a new spiffe binary, in the SPIFFE repo, that does this and more given that the helper is not a SPIRE-specific utility.
> Add banner on maintenance status

- examples/mysql/README.md
There's a link broken in the marked down file to the helper.conf file.
> fix a broken link in README.md

- examples/postgresql/README.md
Fix a broken link in the postgresql example's README.md file
> fix another broken link in README.md

- README.md
- examples/mysql/helper.conf
- examples/mysql/spire-agent.conf
- examples/postgresql/helper.conf
- examples/postgresql/spire-agent.conf
- helper.conf
- helper_envoy.conf
- helper_ghostunnel.conf
- pkg/sidecar/config_test.go
- pkg/sidecar/sidecar_test.go
- test/fixture/config/helper.conf
This PR includes updates to all configuration files, changing the SPIRE agent socket path to the default `"/tmp/spire-agent/public/api.sock"`. Additionally, adjustments have been made to fix the formatting of the table in the `README.md` file.
> Update Config Files with SPIRE Agent Default Socket Path and Fix `README.md` Table Formatting

- .github/workflows/nightly_build.yaml
- .github/workflows/scripts/push-images.sh
Sets up a nightly docker build same as spiffe repos. Code is mostly copied from controller manager.
> Setup nightly build

- README.md
the jwt config vars have changed, 
the documentation in the stanza above is correct but the examples still reference the older config options
this
> docs: readme fix, use jwt_svids instead of jwt_svid_file_name

- .github/workflows/nightly_build.yaml
- .github/workflows/pr_build.yaml
- .github/workflows/release_build.yaml
**Utilize go-version-file in GitHub Actions for Go Setup:**
This PR updates our GitHub Actions by integrating `go-version-file` to specify the Go version during the setup process. This change ensures that the Go environment is consistent with the version defined in the project configuration.
> Use `go-version-file` in Setup go actions

- Dockerfile
Looks like commit eb7a20 broke the docker build (via theDockerfile). Previously only main.go was COPY'd in the docker file. 
Fix is simple, just COPY the whole cmd/spiffe-helper directory rather than just the main.go. 
Looks like the nightly builds have been failing. One suggestion might to add building the docker image to the pr_build tests. I can take a stab at this if desired, I'd mostly just cut and paste from the nightly build minus the pushing. 
Thanks,
Geoff
> add missing files to fix docker build

- .golangci.yml
- Makefile
- pkg/disk/json.go
- Update to latest version of golangci-lint.
- Remove depguard linter, throws a lot of errors. Same was done on spire repo.
- Fix file write permissions
> Update linter to 1.60.3

- .golangci.yml
My reading of https://golangci-lint.run/usage/configuration/#run-configuration and https://golangci-lint.run/usage/linters/#revive indicate we have a couple incorrect keys in the config file.
> Replace unrecognized keys

- .github/tests/it/docker-compose.yaml
- .github/workflows/release_build.yaml
Builds and pushes container to ghcr.io as part of release workflow. Partially addresses #165
> Add docker build to release workflow

- .github/tests/it/client/Dockerfile
- .github/tests/it/go-server/Dockerfile
#174 missed a couple of references to Go 1.22.1.
> Update remaining references to Go 1.22.3

- cmd/spiffe-helper/config/config.go
- pkg/sidecar/config.go
- pkg/sidecar/sidecar.go
- pkg/sidecar/util_posix.go
- pkg/sidecar/util_windows.go
Partially implements: https://github.com/spiffe/spiffe-helper/issues/115
> Add support for signaling an external process via pid file

- cmd/spiffe-helper/config/config.go
- cmd/spiffe-helper/config/config_test.go
- go.mod
- go.sum
Checks for unknown config directives and errors out.
First PR to address https://github.com/spiffe/spiffe-helper/issues/104 (remove camel case config) so that there is an error when camel case config is present.
> Check for unknown config

- README.md
- cmd/spiffe-helper/config/config.go
- cmd/spiffe-helper/config/config_test.go
- cmd/spiffe-helper/config/testdata/helper.conf
- pkg/sidecar/config.go
- pkg/sidecar/sidecar.go
> Add support for extra audiences in JWT SVID

- .github/tests/it/build.sh
- .github/tests/it/client/Dockerfile
- .github/tests/it/docker-compose.yaml
- .github/tests/it/go-server/Dockerfile
- .github/tests/it/mysql/Dockerfile
- .github/tests/it/postgres/Dockerfile
- .github/tests/it/spiffe-helper/Dockerfile
- .github/workflows/pr_build.yaml
The integration tests have a dockerfile to build a spiffe-helper container. This was added before we had a proper container build. This diff removes the redundant dockerfile and uses the one in the root of the repo.
> Remove redundant Dockerfile in tests

- Makefile
Error: can't load config: the Go language version (go1.22) used to build golangci-lint is lower than the targeted Go version (1.23.3)
> Upgrade golangci-lint to fix error

- README.md
- pkg/sidecar/config.go
Per https://github.com/spiffe/spiffe-helper/pull/243#discussion_r1937612176 the -exitWhenReady flag and corresponding ExitWhenReady option were never in a released version. So this obsolete, now-unused field can be deleted without backwards compatibility impact.
The separate PR https://github.com/spiffe/spiffe-helper/pull/243 updates the docs to remove reference to the CLI argument -exitWhenReady.
> Remove ExitWhenReady field

- README.md
Update the README to:
* Explain the various modes in which `spiffe-helper` can be used and why each one might be useful
* Document the previously undocumented pid_file_name config option
* Add explanation of how cmd and cmd_args is interpreted, including:
* double quoting to protect spaces
* escape double quotes by pairing them not with backslashes
* single quotes are not special and don't protect spaces or double quotes
* shell metacharacters are not special
* Warn that stdin is not forwarded, and the exit code of the child process is not forwarded on exit (in fact, spiffe-helper does not exit at all in daemon mode, or run a command at all in non-daemon mode), so spiffe-helper cannot be used as a pass-through wrapper for another command
* Document that an exited `cmd` is re-launched only …
> Document pid_file_name and explain some other flags

- README.md
- pkg/sidecar/sidecar.go
[Presently it's difficult to use `spiffe-helper` to wrap another command](https://github.com/spiffe/spiffe-helper/issues/249), because:
* it doesn't forward its stdin to the command it runs
* it doesn't write the child command's pid anywhere, nor does it forward signals, so there's no easy way to reliably identify and signal the wrapped process
* it uses a stringified argument list when invoking the child process, which is difficult to reliably and correctly escape for all argument variations
(See related: https://github.com/spiffe/spiffe-helper/pull/243, https://github.com/spiffe/spiffe-helper/pull/244)
This PR makes one step toward making it more practical to use the helper as a wrapper command, by forwarding `stdin` to the `cmd` invoked.
Other improvements are needed to make wrapper …
> Forward spiffe-helper's stdin to the 'cmd' invoked in daemon_mode

- go.mod
build the image
```console
$ docker buildx build --platform linux/arm64 --build-arg go_version=1.24.5 -f Dockerfile -t upmdev.azurecr.io/spiffe-helper/spiffe-helper:local . --push
```
check the CVE issues
```console
$ grype upmdev.azurecr.io/spiffe-helper/spiffe-helper:local
✔ Pulled image
✔ Loaded image                                                                                                                              upmdev.azurecr.io/spiffe-helper/spiffe-helper:local
✔ Parsed image                                                                                                          sha256:31ae992b5f7478c6ed6718ed88f17830944c99848dbc8d7ad20ed15c84a4a0f6
✔ Cataloged contents …
```
> fix: bump go version to fix CVE issues
